### ISSUE TITLE
Implementação da home

### ISSUE THREAD

**Issue by GeiseSaunier** [fga-eps-mds/2020.1-Ziguen-Front#1]
| Nome | Assunto | Label | Assignees |
|---|---|---|---|
| Implementação da home | Criar a home da Ziguen| front-end | @GeiseSaunier  |

# Descrição
Implementar a home do sistema, de acordo com o padrão definido no protótipo de alta fidelidade.

# Tarefas

- [x] Implementar a home

# Critérios de Aceitação

- [x] A home estar pronta e funcional de acordo com o protótipo

- [x] Aprovação da Equipe

**Comment by gabrielapivetta** [comment]
Fechando essa issue pois estamos refazendo as telas usando o React
