### ISSUE TITLE
BUG(Request front-end)

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2020.1-Ziguen-Front#16]
| Nome | Assunto| Título| Label | Assignees |
|------|------|------|------|-----|
| Request |  Bug no request| Bug| Bug/front-end | @francisco1code @gabrielapivetta  | 

## Descrição
Foi encontrado um bug na hora em que o front faz um request ao back

## Tarefa 

Resolver e descrever a solução

**Comment by francisco1code** [comment]
Resposta a Tarefa: estava acontecendo o bug por causa de permissões cors, então foi resolvido com a configuração do CORS.

**Comment by gabrielapivetta** [comment]
Fechando essa issue pois estamos refazendo as telas usando o React
