### ISSUE TITLE
Criação da Home

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2020.1-Ziguen-Front#21]
**Descrição da nova feature:**
- Implementação da Home, tela inicial (landing page) onde pode-se pesquisar e visualizar passagens

**Porque essa feature melhoraria o código:**
- É a tela principal da aplicação e facilita a busca por passagens

**Tarefas**

- [X] Criar e estilizar a Home com todas as suas dependências

**Critérios de aceitação**

- [X] Tela pronta e funcional

- [X] Aprovação da equipe

**Comment by Giuulob89** [comment]
A tela ficou pronta e apenas terá uma revisão de código e pequenas alterações.
