### ISSUE TITLE
Implementação da Tela Login

### ISSUE THREAD

**Issue by Giuulob89** [fga-eps-mds/2020.1-Ziguen-Front#3]
| Nome | Assunto | Label | Assignees |
|---|---|---|---|
| Implementação das telas de Login | Criar as telas de Login | front-end | @Giuulob89   |

# Descrição
Implementar a tela de login do passageiro, de acordo com o padrão definido no protótipo de alta fidelidade.

# Tarefas

- [x] Implementar a tela de login do passageiro

# Critérios de Aceitação

- [x] A tela estar pronta e funcional de acordo com o protótipo

- [x] Aprovação da Equipe

**Comment by gabrielapivetta** [comment]
Atualizei a primeira tarefa para tela de login do tripulante e do proprietário

**Comment by gabrielapivetta** [comment]
A tela está praticamente pronta, só faltam pequenos ajustes de design

**Comment by gabrielapivetta** [comment]
> Atualizei a primeira tarefa para tela de login do tripulante e do proprietário

A tarefa foi alterada para apenas a tela do passageiro (que chamávamos de tripulante)

**Comment by gabrielapivetta** [comment]
Fechando essa issue pois estamos refazendo as telas usando o React
