### ISSUE TITLE
Integração front com back

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/2020.1-Ziguen-Front#31]
**Descrição da nova feature:**
- Integrar front-end e back-end

**Porque essa feature melhoraria o código:**
- Site funcional como um todo

**Tarefas**

- [x] Request ao banco de todos os dados

**Critérios de aceitação**

- [x] Testes funcionando
- [x] Dados aparecendo na tela
- [x]  Login e Cadastro de usuários funcionando

**Comment by gabrielapivetta** [comment]
Issue reaberta para finalizarmos o request do front com o back!

**Comment by Giuulob89** [comment]
Gente, encontrei um compilado muito bom sobre a autenticação do login no react. Vou passar os links aqui: https://blog.rocketseat.com.br/autenticacao-react-native-nodejs/ , https://blog.rocketseat.com.br/fluxo-de-autenticacao-com-react-native/ e https://blog.rocketseat.com.br/reactjs-autenticacao/

**Comment by Giuulob89** [comment]
Gente, também acabei de achar um vídeo perfeito que explica direitinho a filtragem de busca. Vou mandar o link aqui e quem se interessar, pode assistir do minuto 25:40 até o minuto 34:05. https://www.youtube.com/watch?v=IeH9qljCN3c

**Comment by liversonp** [comment]
Fechando a issue, a comunicação está funcionando
