### ISSUE TITLE
Criando projeto com Next.js

### ISSUE THREAD

**Issue by GeiseSaunier** [fga-eps-mds/2020.1-Ziguen-Front#9]
| Nome | Labels | Assignees |
| -- | -- | -- |
| Criando projeto com Next.js | Projeto - Next.js | @GeiseSaunier |

# Descrição
Criar o projeto com Next.js

# Tarefas

- [x] Criar o projeto com o Next.js a partir do npm

- [x] Recriar as telas do front-end a partir do Next

# Critérios de Aceitação

- [x] Telas reacriadas

- [x] Aprovação da equipe

**Comment by gabrielapivetta** [comment]
Criamos uma nova branch (newfront) para colocarmos as mudanças com next e react-bootstrap

**Comment by gabrielapivetta** [comment]
Recriamos a Home e a tela de Login com Next.js para testar se a melhoraria a intefração com o back para a R1

**Comment by gabrielapivetta** [comment]
Fechando essa issue pois estamos refazendo as telas usando o React, sem Next.js
